version: "3.7"

services:
  dojo_courses_api:
    container_name: dojo_courses_api
    build: ./backend
    environment:
      - CONNECTION_STRING=postgres://postgres:postgres_pass@dojo_courses_db/postgres-db
    depends_on:
      - dojo_courses_db
    volumes:
      - ./:/app
    networks:
      - network-private
      - network-public

  dojo_courses_web:
    container_name: dojo_courses_web
    build: ./frontend
    environment:
      - API_URL=http://dojo_courses_api:3001/data
    depends_on:
      - dojo_courses_api
    ports:
      - "80:3000"
    volumes:
      - ./:/app
    networks:
      - network-public

          
  dojo_courses_db:
    container_name: dojo_courses_db
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: postgres-db
    volumes:
      - volume-postgres-demo:/var/lib/postgresql/data 
      - volume-postgres-config:/etc/postgres
      - ./sql_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

    networks:
      - network-private
      
volumes: 
    volume-postgres-demo:
    volume-postgres-config:
networks:
    network-public:
    network-private:


